[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11.5"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.14.1",
    "anthropic",
    "requests>=2.32.5",
    "openai>=1.109.1",
]
